let components = [
  { id: 'node_a', name: 'a', attributes: {}, styles: {}, selected: false },
  {
    id: 'node_button',
    name: 'button',
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_div',
    name: 'div',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_footer',
    name: 'footer',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_form',
    name: 'form',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  { id: 'node_h1', name: 'h1', attributes: {}, styles: {}, selected: false },
  { id: 'node_h2', name: 'h2', attributes: {}, styles: {}, selected: false },
  { id: 'node_h3', name: 'h3', attributes: {}, styles: {}, selected: false },
  { id: 'node_h4', name: 'h4', attributes: {}, styles: {}, selected: false },
  { id: 'node_h5', name: 'h5', attributes: {}, styles: {}, selected: false },
  {
    id: 'node_header',
    name: 'header',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  { id: 'node_hr', name: 'hr', attributes: {}, styles: {}, selected: false },
  {
    id: 'node_img',
    name: 'img',
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_input',
    name: 'input',
    attributes: {},
    styles: {},
    selected: false,
  },
  { id: 'node_li', name: 'li', attributes: {}, styles: {}, selected: false },
  {
    id: 'node_main',
    name: 'main',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_nav',
    name: 'nav',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_ol',
    name: 'ol',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  { id: 'node_p', name: 'p', attributes: {}, styles: {}, selected: false },
  {
    id: 'node_section',
    name: 'section',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_span',
    name: 'span',
    attributes: {},
    styles: {},
    selected: false,
  },
  {
    id: 'node_ul',
    name: 'ul',
    items: [],
    attributes: {},
    styles: {},
    selected: false,
  },
];

export default components;
